project:
  type: website
  output-dir: docs
  
website:
  title: "IBM 6400: MOCK UP 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: 
      - icon: github
        href: https://github.com/junetran071/website1
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, June Tran"

format:
  html:
    theme: morph
    toc: true

editor: visual


